[package]
name = "apigpio"
version = "0.1.0"
edition = "2018"

[dependencies]
thiserror = "1"
arrayref = "0.3"
num-traits = "0.2"
num-derive = "0.3"
strum = "0.18"
strum_macros = "0.18"
tokio = { version = "0.2", features = ["full"] }
slotmap = "0.4"
futures-util = "0.3"
